### ISSUE TITLE
Add non TCP/UDP support

### ISSUE THREAD

**Issue by nickrusso42518** [nickrusso42518/narc#3]
Rather than a TCP/UDP source and destination port, there should be an ICMP type and code instead, each of which are unsigned 8-bit integers. Perhaps:
```
---
checks:
  - name: ICMP TEST
    proto: icmp
    type: 8
    code: 0
    (other fields omitted)
```
